// Generated by TvHelpCompiler from demohelp.txt
public final class DemoHelp {
    private DemoHelp() {}

    public static final int hcNocontext            = 0;
    public static final int hcViewer               = 2;
    public static final int hcPuzzle               = 3;
    public static final int hcCalculator           = 4;
    public static final int hcCalendar             = 5;
    public static final int hcAsciiTable           = 6;
    public static final int hcSystem               = 7;
    public static final int hcSAbout               = 8;
    public static final int hcSPuzzle              = 9;
    public static final int hcSCalendar            = 10;
    public static final int hcSAsciiTable          = 11;
    public static final int hcSCalculator          = 12;
    public static final int hcFile                 = 13;
    public static final int hcFOpen                = 14;
    public static final int hcFChangeDir           = 15;
    public static final int hcFDosShell            = 16;
    public static final int hcFExit                = 17;
    public static final int hcWindows              = 18;
    public static final int hcWSizeMove            = 19;
    public static final int hcWZoom                = 20;
    public static final int hcWTile                = 21;
    public static final int hcWCascade             = 22;
    public static final int hcWNext                = 23;
    public static final int hcWPrevious            = 24;
    public static final int hcWClose               = 25;
    public static final int hcOptions              = 26;
    public static final int hcOMouse               = 27;
    public static final int hcOColors              = 28;
    public static final int hcOSaveDesktop         = 29;
    public static final int hcORestoreDesktop      = 30;
    public static final int hcFOFileOpenDBox       = 31;
    public static final int hcFOName               = 32;
    public static final int hcFOFiles              = 33;
    public static final int hcFOOpenBtn            = 34;
    public static final int hcCancelBtn            = 35;
    public static final int hcOpenBtn              = 36;
    public static final int hcFCChDirDBox          = 37;
    public static final int hcOMMouseDBox          = 38;
    public static final int hcOCColorsDBox         = 39;
}
