/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright 2026-present Viktor44
 */
package org.viktor44.jtvision.core;

import static org.viktor44.jtvision.core.EventCodes.evBroadcast;
import static org.viktor44.jtvision.core.EventCodes.evCommand;
import static org.viktor44.jtvision.core.EventCodes.evKeyDown;
import static org.viktor44.jtvision.core.EventCodes.evNothing;

import lombok.Getter;
import lombok.Setter;

/**
 * Core event record passed to every {@code handleEvent} method in the view tree.
 *
 * <p>{@code TEvent} plays a fundamental role in Turbo Vision's event-handling
 * strategy.  Both outside events (mouse and keyboard) and command events
 * generated by communicating views are stored and transmitted as {@code TEvent}
 * instances.
 *
 * <p>The {@link #what} field identifies which kind of event occurred and,
 * therefore, which of the three payload objects ({@link #mouse},
 * {@link #keyDown}, or {@link #message}) carries the relevant data:
 *
 * <ul>
 *   <li><b>Mouse events</b> ({@link EventCodes#evMouse} mask) — {@link #mouse}
 *       is populated.</li>
 *   <li><b>Keyboard events</b> ({@link EventCodes#evKeyDown}) — {@link #keyDown}
 *       is populated.</li>
 *   <li><b>Message events</b> ({@link EventCodes#evMessage} mask, including
 *       {@link EventCodes#evCommand} and {@link EventCodes#evBroadcast}) —
 *       {@link #message} is populated.</li>
 *   <li><b>Nothing events</b> ({@link EventCodes#evNothing}) — the event has
 *       been handled and should be ignored.</li>
 * </ul>
 *
 * <p>This class is the Java equivalent of the Pascal {@code TEvent} variant
 * record defined in {@code DRIVERS.TPU}.  Because Java does not support
 * variant records, the three payload types are held as separate objects that
 * are always present; only the one indicated by {@code what} carries meaningful
 * data.
 *
 * @see EventCodes
 * @see MouseEvent
 * @see KeyDownEvent
 * @see MessageEvent
 */
public class JtvEvent {

    /**
     * Event type discriminator ({@code What} in the original Pascal record).
     * <p>
     * The numeric value describes the kind of event that occurred.  Use the
     * constants in {@link EventCodes} to interpret this field.  Masks such as
     * {@link EventCodes#evMouse} and {@link EventCodes#evMessage} let callers
     * check the event family without enumerating every individual type:
     * <pre>{@code
     * if ((event.getWhat() & evMouse) != 0) { ... }
     * }</pre>
     * <p>
     * When a view finishes handling an event it calls {@code clearEvent},
     * which resets this field to {@link EventCodes#evNothing}.  All views
     * should silently ignore events whose {@code what} equals
     * {@code evNothing}.
     */
	@Getter
	@Setter
    private int what = evNothing;

	/**
     * Mouse event payload ({@code Buttons}, {@code Double}/{@code EventFlags},
     * and {@code Where} in the original Pascal record).
     * <p>
     * Valid when {@link #what} matches the {@link EventCodes#evMouse} mask.
     */
	@Getter
	@Setter
    private MouseEvent mouse = new MouseEvent();

    /**
     * Keyboard event payload ({@code KeyCode} / {@code CharCode} +
     * {@code ScanCode} in the original Pascal record).
     * <p>
     * Valid when {@link #what} equals {@link EventCodes#evKeyDown}.
     */
	@Getter
    private KeyDownEvent keyDown = new KeyDownEvent();

	/**
     * Message event payload ({@code Command} and {@code InfoPtr} /
     * {@code InfoLong} / … in the original Pascal record).
     *
     * <p>Valid when {@link #what} matches the {@link EventCodes#evMessage} mask,
     * i.e. for {@link EventCodes#evCommand} and {@link EventCodes#evBroadcast}
     * events.
     */
	@Getter
	@Setter
    private MessageEvent message = new MessageEvent();

	/**
     * Fills this event as a key-down event.
     *
     * <p>Sets {@link #what} to {@link EventCodes#evKeyDown} and populates the
     * keyboard payload.
     *
     * @param keyCode         full 16-bit key code (high byte = scan code,
     *                        low byte = character code)
     * @param controlKeyState platform-specific modifier key state
     * @param keyChar         Unicode character produced by the key press, or
     *                        {@code KeyEvent.CHAR_UNDEFINED} for non-printable keys
     */
    public void setKeyDownEvent(int keyCode, int controlKeyState, char keyChar) {
        what = evKeyDown;
        keyDown = new KeyDownEvent(keyCode, controlKeyState, keyChar);
    }

    /**
     * Fills this event as a command event.
     *
     * <p>Sets {@link #what} to {@link EventCodes#evCommand} and populates the
     * message payload.  Command events are directed to the focused view first
     * and travel up the view tree until handled.
     *
     * @param command the command code (see {@link CommandCodes})
     * @param infoPtr optional object payload, or {@code null}
     */
    public void setCommand(int command, Object infoPtr) {
        what = evCommand;
        message.setCommand(command);
        message.setInfoPtr(infoPtr);
    }

    /**
     * Fills this event as a broadcast event.
     *
     * <p>Sets {@link #what} to {@link EventCodes#evBroadcast} and populates the
     * message payload.  Broadcast events are delivered to every view in the
     * current group, regardless of focus.
     *
     * @param command the broadcast command code (see {@link CommandCodes})
     * @param infoPtr optional object payload, or {@code null}
     */
    public void setBroadcast(int command, Object infoPtr) {
        what = evBroadcast;
        message.setCommand(command);
        message.setInfoPtr(infoPtr);
    }

    /**
     * Copies all fields from another event into this instance.
     *
     * <p>After this call this event is an independent copy of {@code other};
     * subsequent changes to {@code other} do not affect this instance.
     *
     * @param other the source event to copy from
     */
    public void copyFrom(JtvEvent other) {
        what = other.getWhat();
        mouse = new MouseEvent(
        		new JtvPoint(other.getMouse().getWhere()), 
        		other.getMouse().getEventFlags(), 
        		other.getMouse().getModifiers(), 
        		other.getMouse().getButtons(), 
        		other.getMouse().getWheel()
        );
        keyDown = new KeyDownEvent(
        		other.getKeyDown().getKeyCode(),
        		other.getKeyDown().getModifiers(),
        		other.getKeyDown().getKeyChar()
        );
        message.setCommand(other.getMessage().getCommand());
        message.setInfoPtr(other.getMessage().getInfoPtr());
        message.setInfoInt(other.getMessage().getInfoInt());
        message.setInfoLong(other.getMessage().getInfoLong());
    }
}
