name: Build Examples

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}

    steps:
      - name: Get current date
        id: date
        run: |
          TAG="examples-$(date +'%Y%m%d%H%M')"
          echo "date=$TAG" >> $GITHUB_OUTPUT

  build-examples-windows:
    needs: prepare
    runs-on: windows-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Build
        shell: cmd
        run: |
          call scripts\build-examples.bat
          cd examples\target
          7z a -tzip examples-win.zip *.exe

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          tag_name: ${{ needs.prepare.outputs.date }}
          files: examples/target/examples-win.zip

  build-examples-macos:
    needs: prepare
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Build
        shell: bash
        run: |
          scripts/build-examples.sh
          cd examples/target
          7z a -tzip examples-macos.zip demo dir editor forms mmenu palette

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          tag_name: ${{ needs.prepare.outputs.date }}
          files: examples/target/examples-macos.zip

  build-examples-linux:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'graalvm'

      - name: Build
        shell: bash
        run: |
          scripts/build-examples.sh
          cd examples/target
          7z a -tzip examples-linux.zip demo dir editor forms mmenu palette

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: false
          tag_name: ${{ needs.prepare.outputs.date }}
          files: examples/target/examples-linux.zip
