name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['8', '17', '25']

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Test
        run: mvn clean package --batch-mode --no-transfer-progress

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: central-sonatype
          server-username: CENTRAL_REPO_USER 
          server-password: CENTRAL_REPO_PASSWORD
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy
        run: |
          cat ~/.m2/settings.xml;

          mvn deploy --batch-mode --no-transfer-progress -DskipTests
